second commit
front-end-by-rimantas/40-grupe-portfolio-braintech pull request #86
Opened 2022-11-15 16:08 UTC by EvgenySivaykin

2022-11-15 16:35 UTC, liepsneletech requested changes
Looks nice, just some small fixes:
1. Teksto spalva turi būti --dgray
![image](https://user-images.githubusercontent.com/114074935/201973336-456c7d02-f04a-4da9-bac8-6cc29bbb7531.png)

2. Cards in mobile need gaps:
![image](https://user-images.githubusercontent.com/114074935/201973848-8eed3fa9-9bef-4d1b-b1b4-579cf89ba6c9.png)

3. Gap between numbers in mobile, their text color and font weight:
![image](https://user-images.githubusercontent.com/114074935/201974314-a9ef4a7a-3c30-47e6-bd2d-cd8bcec74249.png)

4. Bigger gap needed:
![image](https://user-images.githubusercontent.com/114074935/201975053-7646f731-7a97-438c-a893-077a0ae3090e.png)

2022-11-15 17:10 UTC, EvgenySivaykin commented
Padaryta

2022-11-15 19:39 UTC, liepsneletech submitted a review, later dismissed

2022-11-16 06:51 UTC, EvgenySivaykin commented
All done

2022-11-16 10:39 UTC, zilva149 approved these changes

2022-11-16 10:41 UTC, merged